Database:
  type: "MariaDB"
  host: "localhost:3306"
  dbname: "charl_craft"
  user: "user"
  password: "password"

vsc_command:
  text1: ""
  text2: ""
  text3: ""

board_setting:
  Hours:
    Format: ""
  Boards_Toggle_Message:
    ON: ""
    OFF: ""

items:
  id:
    POISONOUS_POTATO:
      1:
        name: "100チャコイン"
        Lore:
          - "右クリックで100チャゲットできる。"
          - ""
        Money: 100.0
      2:
        name: "1000チャ紙幣"
        Lore:
          - "右クリックで1000チャゲットできる。"
          - ""
        Money: 1000.0


#
#色の書き方：
#${AQUA}
#

main_board:
  ui_Name: "1"
  ui_Title: "ちゃるくら！"
  content:
    title:
      - "== ちゃるくら！ =="
      - ""
    message:
      - "a"
      - "a"
      - "a"

