name: VSCCore
main: com.charlotte04.vsccore.VSCCore
version: 1.0.1
api-version: 1.19
load: STARTUP
softdepend: [Jecon,PlaceholderAPI,Vault]

commands:
  vs_money:
    usage: ""
  charl:
    usage: ""
  menu:
    usage: ""